
        # QT_SBOM_BUILD_TIME be set to FALSE at install time, so don't override if it's set.
        # This allows reusing the same cmake file for both build and install.
        if(NOT DEFINED QT_SBOM_BUILD_TIME)
            set(QT_SBOM_BUILD_TIME TRUE)
        endif()
        if(NOT QT_SBOM_OUTPUT_PATH)
            set(QT_SBOM_OUTPUT_DIR "D:/Exam_Project/qtcharts-build/qt_sbom/sbom")
            set(QT_SBOM_OUTPUT_PATH "D:/Exam_Project/qtcharts-build/qt_sbom/sbom/qtcharts-6.8.3.spdx")
            set(QT_SBOM_OUTPUT_PATH_WITHOUT_EXT "D:/Exam_Project/qtcharts-build/qt_sbom/sbom/qtcharts-6.8.3")
            file(MAKE_DIRECTORY "D:/Exam_Project/qtcharts-build/qt_sbom/sbom")
        endif()
        set(QT_SBOM_VERIFICATION_CODES "")
        include("D:/Exam_Project/qtcharts-build/qt_sbom/append_document_to_staging.cmake")
include("D:/Exam_Project/qtcharts-build/qt_sbom/SPDXRef-Package-qtcharts-qt-module-Charts.cmake")
include("D:/Exam_Project/qtcharts-build/qt_sbom/SPDXRef-PackagedFile-qt-module-Charts.cmake")
include("D:/Exam_Project/qtcharts-build/qt_sbom/SPDXRef-PackagedFile-qt-module-Charts-ImportLibrary.cmake")
include("D:/Exam_Project/qtcharts-build/qt_sbom/SPDXRef-Package-qtcharts-qt-module-ChartsQml.cmake")
include("D:/Exam_Project/qtcharts-build/qt_sbom/SPDXRef-PackagedFile-qt-module-ChartsQml.cmake")
include("D:/Exam_Project/qtcharts-build/qt_sbom/SPDXRef-PackagedFile-qt-module-ChartsQml-ImportLibrary.cmake")
include("D:/Exam_Project/qtcharts-build/qt_sbom/SPDXRef-Package-qtcharts-qt-plugin-qtchartsqml2.cmake")
include("D:/Exam_Project/qtcharts-build/qt_sbom/SPDXRef-PackagedFile-qt-plugin-qtchartsqml2.cmake")
include("D:/Exam_Project/qtcharts-build/qt_sbom/SPDXRef-LicenseRef-Qt-Commercial-0.cmake")
include("D:/Exam_Project/qtcharts-build/qt_sbom/DocumentRef-qtbase.cmake")
include("D:/Exam_Project/qtcharts-build/qt_sbom/DocumentRef-qtdeclarative.cmake")
        if(QT_SBOM_BUILD_TIME)
            message(STATUS "Finalizing SBOM generation in build dir: ${QT_SBOM_OUTPUT_PATH}")
            configure_file("D:/Exam_Project/qtcharts-build/qt_sbom/staging-qtcharts.spdx.in" "${QT_SBOM_OUTPUT_PATH}")
            
        endif()
